project:
  type: website
  output-dir: docs

website:
  title: "Christian Etherson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Professional Summary
      - href: portfolio.qmd
        text: Data Work Samples
      - href: articles.qmd
        text: Articles
      - href: photography.qmd
        text: Photography
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

